# Reference: https://github.com/pokgak/citf-graphs/blob/main/.github/workflows/update_graphs.yml
# This is a basic workflow to help you get started with Actions

name: Update Graph

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  schedule:
    - cron: "30 0 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      # - name: Cache pip
      #   uses: actions/cache@v2
      #   with:
      #     # This path is specific to Ubuntu
      #     path: ~/.cache/pip
      #     # Look to see if there is a cache hit for the corresponding requirements file
      #     key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
      #     restore-keys: |
      #       ${{ runner.os }}-pip-
      #       ${{ runner.os }}-
      # - name: Install dependencies
      #   run: pip3 install -r requirements.txt

      - name: Fetch latest data & generate new graph
        run: python3 main.py
        
      - id: get-date
        run: echo "::set-output name=value::$(date --iso-8601)"

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "bot: update graph for ${{ steps.get-date.outputs.value }}"

